# Generated by Django 2.1.5 on 2019-05-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='Contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='persons',
            name='Email',
            field=models.CharField(default='no email', max_length=255),
        ),
        migrations.AlterField(
            model_name='persons',
            name='Game',
            field=models.CharField(default='no game', max_length=255),
        ),
        migrations.AlterField(
            model_name='persons',
            name='Password',
            field=models.CharField(default='no pass', max_length=255),
        ),
        migrations.AlterField(
            model_name='persons',
            name='Username',
            field=models.CharField(default='No username', max_length=255),
        ),
    ]
